SET time_zone = '+01:00';

USE bjtob17;

CREATE TABLE IF NOT EXISTS user
(
  user_id        INT AUTO_INCREMENT PRIMARY KEY,

  username       VARCHAR(255) NOT NULL UNIQUE,
  hashedPassword VARCHAR(255) NOT NULL,
  firstName      VARCHAR(255) NOT NULL,
  lastName       VARCHAR(255) NOT NULL,
  zip            INT          NOT NULL,
  city           VARCHAR(255) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  phone          VARCHAR(30)  NOT NULL,

  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS photo
(
  photo_id   INT AUTO_INCREMENT PRIMARY KEY,

  title      VARCHAR(255) NOT NULL,
  caption    VARCHAR(255) NOT NULL,
  imgName    VARCHAR(255) NOT NULL,
  imgData    BLOB         NOT NULL,
  uploadDate INT          NOT NULL DEFAULT UNIX_TIMESTAMP(),
  author_id  INT          NOT NULL REFERENCES user (user_id),

  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);