DROP DATABASE IF EXISTS dpete17;

CREATE DATABASE dpete17;

use dpete17;

CREATE TABLE account (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(150) NOT NULL
);

CREATE TABLE image (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(150) UNIQUE NOT NULL,
    uploaded_at TIMESTAMP NOT NULL
);

CREATE TABLE sent (
    account_id BIGINT UNSIGNED,
    id BIGINT UNSIGNED,
    PRIMARY KEY (account_id, id)
);