version: '3'

services:
  web:
    image: bjarkt/php:7.3
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    ports:
      - "3000:80"

  db:
    image: mariadb:10.3.12
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: assignment_1
    ports:
        - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data:
