web:
#  image: php:7.3-apache
  build: './'
  ports:
    - "8080:80"
  links:
    - db
  volumes:
    - './:/var/www/html/'

db:
  image: 'mariadb:10.4'
  restart: always
  volumes:
    - './mysql:/var/lib/mysql'
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: foobar
    MYSQL_PASSWORD: foobar123
    MYSQL_DATABASE: assignment1
