CREATE TABLE images (
idImg int(20) AUTO_INCREMENT PRIMARY KEY NOT NULL,
idUser int(20) KEY NOT NULL,
uidUsers TINYTEXT NOT NULL,
path LONGTEXT NOT NULL,
name LONGTEXT NOT NULL,
FOREIGN KEY (idUser) REFERENCES users(idUsers)
);