SET time_zone='+01:00';

CREATE TABLE IF NOT EXISTS user (
  user_id INT AUTO_INCREMENT PRIMARY KEY,

  username VARCHAR(255) NOT NULL UNIQUE,
  hashedPassword VARCHAR(255) NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photo (
  photo_id INT AUTO_INCREMENT PRIMARY KEY,

  title varchar(255) NOT NULL,
  caption varchar(255) NOT NULL,
  imgName varchar(255) NOT NULL,
  uploadDate INT DEFAULT UNIX_TIMESTAMP(),
  author_id INT NOT NULL REFERENCES user(user_id),

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
