ALTER TABLE users
  ADD firstName VARCHAR(255) NOT NULL,
  ADD lastName VARCHAR(255) NOT NULL,
  ADD zip INT NOT NULL,
  ADD city VARCHAR(255) NOT NULL,
  ADD email VARCHAR(255) NOT NULL,
  ADD phone VARCHAR(30) NOT NULL;
