version: '3'

services:
  db:
    image: mariadb:10.3.12
    volumes:
      - "./migrations/:/docker-entrypoint-initdb.d/"
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bjtob17
    ports:
      - "3306:3306"

volumes:
  db_data:
