<html>
    <head>
        <link rel="stylesheet" href="login_style.css">
        <meta name="viewport" content = "width=device-width, initial-scale=1.0">
    </head>
    <body>
    <div class = 'login'>
        <img src = "images/spacebook.png" alt="Logo"> 
        <form method="post">
            <div class="form_input">
                <label>Username:</label>
                <input type="text" name="login" value="">
            </div>
            
            <div class="form_input">
                <label>Password:</label>
                <input type="password" name="password" value="" >
            </div>
            <input type="submit" name="submit" id="submit">
        </form>
        <p>Not already a user? Click <a href='register.php'>here</a> to register now.</p>
    </div>
    <div class = "spacebook-images">
        <img src="images/space_cat.jpg">
    </div>
        
    <div class = "spacebook-text">
        <p>Space, also known as outer space, is the near-vacuum between celestial bodies.[1] It is where everything (all of the planets, stars, galaxies and other objects) is found.
<br>
On Earth, space begins at the Kármán line (100 km above sea level).[2] This is where Earth's atmosphere is said to stop and outer space begins. This is not a natural boundary but is a convention used by scientists and diplomats.
<br>

However, the space near Earth is quite crowded by astronomical standards. A list of spaces goes like this:
<br>

Geospace is the region of outer space near Earth. Geospace includes the upper region of the atmosphere and the magnetosphere.[3] The Van Allen radiation belt lies within the geospace. The space inside the magnetosphere is protected from radiation from the Sun. It has a low level of electrically charged particles.
Interplanetary space is the space around the Sun and planets of the Solar System. It has the solar wind, a continuous stream of charged particles from the Sun. This stream creates a very thin atmosphere (the heliosphere) for billions of miles or kilometers into space. 
Interplanetary space has the magnetic field generated by the Sun.[4] Planets such as Jupiter, Saturn, Mercury and the Earth also have magnetospheres. These magnetic fields can trap particles from the solar wind and other sources, creating belts of magnetic particles such as the Van Allen radiation belt. Planets without magnetic fields, such as Mars, have their atmospheres gradually stripped off by the solar wind.[5]
Interstellar space is the physical space within a galaxy not occupied by stars or their planetary systems. It continues to the edges of the galaxy, where it fades into the intergalactic void. Most of the mass in this space is made up of single hydrogen atoms, fewer helium atoms and a few heavier atoms formed in stars. Supernovae blow some of their atoms huge distances. 
A number of molecules and tiny 0.1 μm dust particles do exist in interstellar space.[6] About four new types of molecule are discovered each year. Large regions of higher density matter known as molecular clouds allow chemical reactions to occur. This incudes organic polyatomic species. Much of this chemistry is driven by collisions.
Intergalactic space does have 'cosmic voids' between the large-scale structures of the universe.</p>
    </div>
    <?php
    require "database.php";
    if (session_status() == PHP_SESSION_NONE) {
        session_start();
    }

    if(isset($_POST['logout'])) {
        $_SESSION["user_name"] = false;
    }

    if(isset($_POST['submit']) && strlen($_POST["login"])>0 && authenticate($_POST['login'], $_POST['password'])) {
        $_SESSION["user_name"] = $_POST['login'];
        header('Location: index.php', true, 302);
        die();
    } else if (isset($_POST['submit'])) {
        echo "Wrong username or password!";
    }


    ?>
    
    </body>




</html>


